### ISSUE TITLE
cpp: define isl::managed_copy() overload

### ISSUE THREAD

**Issue by ftynse** [PollyLabs/isl#9]
I found myself writing
`isl::manage(isl_whatever_copy(o));  // manage releases!`
multiple times.

Can we generate an overloaded function
```c
isl::whatever managed_copy(__isl_keep isl_whatever *w) {
  return isl::manage(isl_whatever_copy(w));
}
```
as a shortcut for these cases?

**Comment by ftynse** [comment]
While the idea of the C++ interface is not to use raw pointers, other isl-dependent libraries (read ppcg) may use raw pointers and feature no C++ interface.

**Comment by tobiasgrosser** [comment]
Sounds very reasonable. Should be a rather simple change and this is indeed a pattern that arises often. Would be glad to see a PR.

**Comment by ftynse** [comment]
This hack may work, but it will break the consistency of __isl_keep/__isl_take because manage is __take.

```c++
template <typename T>
auto managed_copy(__isl_keep T t) -> decltype(isl::manage(t)) {
  auto x = isl::manage(t);
  auto copy = x;
  x.release();
  return copy;
}
```

**Comment by tobiasgrosser** [comment]
I would just extend the generator. Should only be a couple of lines and
can follow precisely the pattern isl::manage is generated.

Best,
Tobias

**Comment by tobiasgrosser** [comment]
This issue has been resolved.
